# Generated by Django 3.1.4 on 2021-07-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lahan',
            name='id_kab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kabupaten', unique=True, verbose_name='Nama kabupaten'),
        ),
    ]
