# Generated by Django 3.1.4 on 2021-07-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210711_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lahan',
            name='id_kab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kabupaten', verbose_name='Nama kabupaten'),
        ),
    ]
