# Generated by Django 3.1.4 on 2021-07-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210711_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabupaten',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
