# Generated by Django 3.1.4 on 2021-07-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_kabupaten_alamat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kabupaten',
            name='alamat',
        ),
        migrations.AddField(
            model_name='pupuk',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
    ]
