# Generated by Django 3.1.4 on 2021-07-21 18:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210716_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='irigasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.FileField(blank=True, null=True, upload_to=website.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['kmz']), website.models.file_size])),
                ('id_kab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kabupaten', verbose_name='Nama kabupaten')),
            ],
        ),
    ]
